version: 2.1

jobs:
  gradle-build:
    docker:
      - image: circleci/openjdk:17-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Spustenie ./gradlew clean build
          command: ./gradlew clean build

workflows:
  build-workflow:
    jobs:
      - gradle-build