version: 2.1

jobs:
  gradle-build:
    docker:
      - image: cimg/openjdk:17.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Udeľ prístupové práva pre gradlew
          command: chmod +x ./gradlew

      - run:
          name: Spustenie ./gradlew clean build
          command: ./gradlew clean build

workflows:
  build-workflow:
    jobs:
      - gradle-build